name: dotnet-ci

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - ".github/workflows/**"
  pull_request:
      paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Get short SHA
      run: echo "SHA7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
        
    - name: Setup Android Ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27d
        add-to-path: true
        local-cache: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v5.1.0
      with:
        dotnet-version: "10.0"
        cache: true
        cache-dependency-path: ./src/PhiInfo.Android/packages.lock.json

    - name: Setup Tpk
      run: | 
        curl -L -o tpk.zip https://nightly.link/AssetRipper/Tpk/workflows/type_tree_tpk/master/uncompressed_file.zip
        unzip tpk.zip uncompressed.tpk
    
    - name: Add GitHub NuGet source
      run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Restore PhiInfo
      run: | 
        dotnet workload install android
        dotnet restore ./src/Shua.Zip/Shua.Zip.csproj
        dotnet restore ./src/PhiInfo.Core/PhiInfo.Core.csproj
        dotnet restore ./src/PhiInfo.Processing/PhiInfo.Processing.csproj
        dotnet restore ./src/PhiInfo.CLI/PhiInfo.CLI.csproj
        dotnet restore ./src/PhiInfo.Android/PhiInfo.Android.csproj

    - name: Pack NuGet Packages
      run: |
        mkdir -p nuget
        dotnet pack ./src/PhiInfo.Core/PhiInfo.Core.csproj --configuration Release --no-restore -p:GitHash=$SHA7 -o ./nuget
        dotnet pack ./src/Shua.Zip/Shua.Zip.csproj --configuration Release --no-restore -p:GitHash=$SHA7 -o ./nuget
        dotnet pack ./src/PhiInfo.Processing/PhiInfo.Processing.csproj --configuration Release --no-restore -p:GitHash=$SHA7 -o ./nuget
        
    - name: Upload NuGet Packages
      uses: actions/upload-artifact@v7
      with:
        name: Nuget
        path: ./nuget/*

    - name: Push NuGet Packages
      run: for pkg in ./nuget/*.nupkg; do dotnet nuget push "$pkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate; done
            
    - name: Build PhiInfo.CLI
      run: | 
        dotnet build ./src/PhiInfo.CLI/PhiInfo.CLI.csproj --configuration Release --no-restore -p:GitHash=$SHA7
        cp uncompressed.tpk ./src/PhiInfo.CLI/bin/Release/net10.0/classdata.tpk

    - name: Upload PhiInfo.CLI artifacts
      uses: actions/upload-artifact@v7
      with:
        name: PhiInfo.CLI
        path: ./src/PhiInfo.CLI/bin/Release/net10.0/**

    - name: Publish PhiInfo.CLI-Android
      run: | 
        dotnet publish ./src/PhiInfo.CLI/PhiInfo.CLI.csproj --configuration Release -r linux-bionic-arm64 -p:GitHash=$SHA7
        cp uncompressed.tpk ./src/PhiInfo.CLI/bin/Release/net10.0/linux-bionic-arm64/publish/classdata.tpk

    - name: Upload PhiInfo.CLI-Android
      uses: actions/upload-artifact@v7
      with:
        name: PhiInfo.CLI-Android
        path: ./src/PhiInfo.CLI/bin/Release/net10.0/linux-bionic-arm64/publish/**

    - name: Publish PhiInfo.Android
      run: |
        mkdir -p ./src/PhiInfo.Android/Assets/
        cp uncompressed.tpk ./src/PhiInfo.Android/Assets/classdata.tpk
        dotnet publish ./src/PhiInfo.Android/PhiInfo.Android.csproj --configuration Release -r android-arm64 -p:GitHash=$SHA7

    - name: Upload PhiInfo.Android
      uses: actions/upload-artifact@v7
      with:
        archive: false
        path: ./src/PhiInfo.Android/bin/Release/net10.0-android/android-arm64/publish/dev.phigros_labs.PhiInfo-Signed.apk

   
